<?php
/**
 * CompanyApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Erive\Delivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ERIVE.delivery API
 *
 * ERIVE.delivery (formerly GREEN TO HOME) API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@erive.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Erive\Delivery\Test\Api;

use \Erive\Delivery\Configuration;
use \Erive\Delivery\ApiException;
use \Erive\Delivery\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CompanyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Erive\Delivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CompanyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteParcelById
     *
     * delete Parcel.
     *
     */
    public function testDeleteParcelById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getParcelById
     *
     * returns Parcel details by id.
     *
     */
    public function testGetParcelById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for submitParcel
     *
     * submit new Parcel.
     *
     */
    public function testSubmitParcel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateParcelById
     *
     * update Parcel status.
     *
     */
    public function testUpdateParcelById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
